### ISSUE TITLE
installScript not working

### ISSUE THREAD

**Issue by muralikodali** [NJOYSoftware/git-updater#3]
there is installscript option which can be useful to compile c  programs and some other programs.it is not working as intended.
 it is exiting with following output without compiling the program : 

```
Fetching origin
Already up to date.
make: Nothing to be done for '/home/xxxx/programs/gitbag/iotop/Makefile'.
Repository 'https://github.com/Tomas-M/iotop' updated.
```
how to use make commands or scripts with installscript option? can you please explain more in documentation.

**Comment by NJOYSoftware** [comment]
Could you please tell me what you have written in the installScript field?

Also, could you try the following methods:
1) Run `make clean` before executing `git-updater` with the option `forceInstall: y`. Does it has the same output?
1) Add an executable file in the same directory of the Makefile (for example named `install.sh`) and put the path to `install.sh` in the installScript field (with the content below). Does it has the same output?

install.sh content:
```
#!/bin/bash
make
```

**Comment by muralikodali** [comment]
Thanks for reply.
i have tried it. for some programs 'make' is getting errors due to env problems. cd into git directory before 'make' command solved the problem.

**Comment by NJOYSoftware** [comment]
This is how the install script is executed: `system(("(" ~ key.installScriptPath() ~ ")").toStringz())`.

I'll break it down:
1) `"(" ~ key.installScriptPath() ~ ")"` takes the value of the field installScript from the Gitfile and put it between parenthesis (which make the command to be run in a subshell);
1) `.toStringz()` converts the said string, which is a D string, into a null-terminated array of chars, which is the type required by the function `system`;
1) `system(...)` executes its argument in a shell, so it is like pasting the string in a bash terminal and pressing enter.

`system` uses the same working directory as the program (if the working directory has not been changed), so it is better to prepend to the command to be run a string like `cd /absolute/path/to/git/directory && ` to be sure the command is executed in the correct folder.

-----
The output line:
> `make: Nothing to be done for '/home/xxxx/programs/gitbag/iotop/Makefile'.`

means that the make target is up to date, so there is "nothing to be done", which means the target is already built.

Maybe you have run `git-updater` before, you didn't see that make built the program (but I have my faults, there is not even a minimal output), and you run `git-updater` again, and it eventually returned the quoted line.

-----
The intended (by me) way to use the installScript field is using it to point to a bash script which is executed.
The minimal bash script content to build a project with make can resemble to the following:
```
#!/bin/bash
cd /into/the/right/directory
make
```

Anyway, I'll add a better explanation about this topic in the readme.

**Comment by muralikodali** [comment]
I have done as suggested by you. It compiled without any errors.

I have a problem cloning non-existent repo in to  the local path.

Following are my configuration options :

  updateOnly: n
  forceInstall: y
  createMissingDirs: y

  - host: https://github.com
    author: figsoda
    name: mmtc
    commit: latest on master
    localPath: /home/murali/programs/gitbag

when i ran git-updater with above configuration, i have expected to clone therepo in to local path.It didn't happen. but the git-updater shown the output as follows :

```
Fetching origin
Already up to date.
Repository 'https://github.com/figsoda/mmtc' updated.
```

is there any configuration error or the program can't clone new repo in to local path?

I have used many git based programs like mrh,gitup,lazygit etc. They can be used to find the status of repo or pull the changes from the remote repository.  This program (git-updater) differs from those programs and also looks promising for repo maintenance as we can update and compile so many repos (upto 50 repos in my case) at the same time, just like system update and eases the maintenance of git repos.

**Comment by NJOYSoftware** [comment]
When the selected repository is not present locally, `git-updater` does not use `git clone` as it copies the whole repository, while `git-updater` aims to be the lightest possible. In order to "clone" the remote repo, `git-updater` goes into the directory pointed by "localPath", executes `git init` and then it fetches tags and commits.

If you want the new repo to be inside that directory in its own folder (let's call it "repo-folder"), in localPath there should be written `/home/murali/programs/gitbag/repo-folder`.

With this value and the option `createMissingDirs` enabled, you should see that the folder "repo-folder" has been created and it has the content of the latest commit.

Given this, localPath should point to the directory in which the repo will live, that is, in your case I guess it will be `/home/murali/programs/gitbag/mmtc`, assuming that `/home/murali/programs/gitbag` is the directory containing all the repository you are interested in.

Last thing, it seems there is an initialized git repository in "/home/murali/programs/gitbag", if it is not intended make sure to delete all the git-related files and folders (like `.git` or `.gitignore`).

**Comment by muralikodali** [comment]
one repo "figsoda/mmtc" giving the following error.

```
remote: Enumerating objects: 78, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 590 (delta 47), reused 52 (delta 24), pack-reused 512
Receiving objects: 100% (590/590), 110.90 KiB | 298.00 KiB/s, done.
Resolving deltas: 100% (388/388), done.
From https://github.com/figsoda/mmtc
 * [new branch]      main       -> origin/main
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v0.1.1     -> v0.1.1
 * [new tag]         v0.2.0     -> v0.2.0
 * [new tag]         v0.2.1     -> v0.2.1
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Execution error for apply: Selected last reference could not be retrieved.

```

**Comment by NJOYSoftware** [comment]
The repository you are trying to update does not have a `master` branch, so you have to change the tracked branch in the commit field.

I'm closing this issue as we are going off topic. If you encounter other types of error, feel free to open a new issue.

**Comment by muralikodali** [comment]
changing the  following line in configuration file worked.

  commit: latest on master  to

```
commit: latest on main
```
